import type { Metadata } from "next";
import "./globals.css";
import Header from "@/components/layout/header";
import { AppProvider } from "@/components/providers/appProvider";
import { StoreProvider } from "@/components/providers/storeProvider";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <StoreProvider>
          <AppProvider>
            <Header />
            {children}
          </AppProvider>
        </StoreProvider>
      </body>
    </html>
  );
}
