import type { Metadata } from "next";
import "./globals.css";
import Link from "next/link";
import Image from "next/image";
import { ButtonAsChild } from "@/components/buttons/buttonAsChild";
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <header>
          <div className="flex justify-between items-center">
            <div
              id="logo"
              className="w-14 h-14 rounded-full relative overflow-hidden"
            >
              <Image
                src={"/logo.jpg"}
                alt="logo"
                fill
                className="object-cover"
              />
            </div>
            <nav>
              <ul>
                <li className="inline m-2">
                  <ButtonAsChild href="/register">Register</ButtonAsChild>
                </li>
                <li className="inline m-2">
                  <ButtonAsChild href="/login">Login</ButtonAsChild>
                </li>
              </ul>
            </nav>
          </div>
        </header>
        {children}
        {/* <footer>footer</footer> */}
      </body>
    </html>
  );
}
